polls/urls.py
from django.contrib import admin
from django.urls import path

from polls import views
from .views import index

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name="detail"),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

untitled/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls'))
]

polls/models.py
from django.db import models

# Create your models here.
from django.db import models
import datetime
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse

from polls.models import Question, Choice


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'index.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/detail.html
{% extends "include/base2.html" %}
{% load staticfiles %}

{% block content %}
<h2>{{ question.question_text }}</h2>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>
<br>
{{ samplex }}
<br>===========================
{% for var in samplex %}
    <br>
    {{ var }}
{% endfor %}
{% endblock %}

polls/templates/include/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

{% include "./head.html" %}
{% block css %}{% endblock %}

<body id="page-top">
	{% include "./menu.html" %}
	<div class="container-fluid p-0">

  <section class="resume-section p-3 p-lg-5 d-flex d-column" id="about">
    <div class="my-auto">
      <h1 class="mb-0">
        <span class="text-primary">Nungky Nurdianto</span>
      </h1>
      <div class="subheading mb-5">NIM : L200140148
        <a href="mailto:name@email.com">nungkinurdyanto19@gmail.com</a>
      </div>
      <p class="mb-5">Aplikasi cloud computing untuk server berbasis django dengan google app engine.</p>

    </div>
  </section>

  <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="experience">
    <div class="my-auto">
      <h2 class="mb-5">Available Question</h2>

      <div class="resume-item d-flex flex-column flex-md-row mb-5">
        <div class="resume-content mr-auto">
        	{% block content %}
        	    
        	{% endblock content %}
        </div>
      </div>

    </div>

  </section>

</div>
	

</body>

{% include "./foot.html" %}
{% block js %}{% endblock %}
</html>

polls/templates/include/base2.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

{% include "./head.html" %}
{% block css %}{% endblock %}

<body id="page-top">
	{% include "./menu2.html" %}
	<div class="container-fluid p-0">
  <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="experience">
    <div class="my-auto">
      {% block content %}
          
      {% endblock content %}

    </div>

  </section>

</div>
	

</body>

{% include "./foot.html" %}
{% block js %}{% endblock %}
</html>

polls/templates/include/content.html

<div class="container-fluid p-0">

  <section class="resume-section p-3 p-lg-5 d-flex d-column" id="about">
    <div class="my-auto">
      <h1 class="mb-0">
        <span class="text-primary">Nungky Nurdianto</span>
      </h1>
      <div class="subheading mb-5">NIM : L200140148
        <a href="mailto:name@email.com">nungkinurdyanto19@gmail.com</a>
      </div>
      <p class="mb-5">Aplikasi cloud computing untuk server berbasis django dengan google app engine.</p>

    </div>
  </section>

  <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="experience">
    <div class="my-auto">
      <h2 class="mb-5">Available Question</h2>

      <div class="resume-item d-flex flex-column flex-md-row mb-5">
        <div class="resume-content mr-auto">

          <h3 class="mb-0">Senior Web Developer</h3>
          <div class="subheading mb-3">Intelitec Solutions</div>
          <p>Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal that has evolved from generation X is on the runway heading towards a streamlined cloud solution. User generated content in real-time will have multiple touchpoints for offshoring.</p>
        </div>
        <div class="resume-date text-md-right">
          <span class="text-primary">March 2013 - Present</span>
        </div>
      </div>

    </div>

  </section>

</div>


polls/templates/include/foot.html
{% load static%}
<script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
<script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
<script src="{% static "vendor/jquery-easing/jquery.easing.min.js" %}"></script>
<script src="{% static "js/resume.min.js" %}"></script>

polls/templates/include/head.html
  <head>
{% load static%}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

    <title></title>
  
  <link href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

  <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:100,200,300,400,500,600,700,800,900" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
  
  <link href="{% static "vendor/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet">
  <link href="{% static "vendor/devicons/css/devicons.min.css" %}" rel="stylesheet">
  <link href="{% static "vendor/simple-line-icons/css/simple-line-icons.css" %}" rel="stylesheet">

  <link href="{% static "css/resume.min.css" %}" rel="stylesheet">

</head>

polls/templates/include/menu.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
  <a class="navbar-brand js-scroll-trigger" href="#page-top">
    <span class="d-block d-lg-none"></span>
    <span class="d-none d-lg-block">
      <img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="img/profile.jpg" alt="">
    </span>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link js-scroll-trigger" href="#about">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link js-scroll-trigger" href="#experience">Question</a>
      </li>

    </ul>
  </div>
</nav>

polls/templates/include/menu2.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
  <a class="navbar-brand js-scroll-trigger" href="#page-top">
    <span class="d-block d-lg-none"></span>
    <span class="d-none d-lg-block">
      <img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="img/profile.jpg" alt="">
    </span>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link js-scroll-trigger" href="{% url 'polls:index' %}">Home</a>
      </li>
    </ul>
  </div>
</nav>

polls/templates/index.html
{% extends "include/base.html" %}
{% block content %}
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}

        <li><h3 class="mb-0"><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></h3></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% endblock %}

polls/templates/results.html
{% extends "include/base2.html" %}
{% load staticfiles %}

{% block content %}
    <h2>{{ question.question_text }}</h2>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

{% endblock content %}